// src/components/navbar.tsx
"use client";

import logo from "@/app/icon.svg";
import { Session } from "next-auth";
import { Plus_Jakarta_Sans } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { UserButton } from "./userbutton";

const font = Plus_Jakarta_Sans({ weight: "400", subsets: ["latin"] });

export function NavBar({ session }: { session: Session | null }) {
  return (
    <nav className="p-3 flex justify-between bg-blue-950 shadow-md md:text-xl">
      <Link href="/">
        <Image
          src={logo}
          height={24}
          width={24}
          alt="logo"
          className="cursor-pointer"
        />
      </Link>
      <Link href={"/"} className={font.className}>
        LECTCHECK
      </Link>
      <UserButton session={session} />
    </nav>
  );
}

// src/routes/navbar.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { Card } from "$components";
  import type { Session } from "$lib/auth";

  const session: Session = $page.data.session;
</script>

<Card
  class="sticky top-2 z-10 m-2 flex justify-between items-center rounded-lg"
>
  <a href="/" class="flex gap-3">
    <img
      src="https://lectcheck.vercel.app/_next/static/media/icon.143e074d.svg"
      alt="logo"
      width="20"
      height="20"
    />
    LECTCHECK
  </a>
  <div class="flex gap-3">
    <a href="/">Home</a>
    <a href="/">About</a>
    {#if !session}
      <a href="/login">Log In</a>
    {:else}
      <a href="/account">Account</a>
    {/if}
  </div>
</Card>
