// src/components/footer.tsx
import { Dot } from "lucide-react";
import Link from "next/link";
import { PropsWithChildren } from "react";

export function Footer() {
  return (
    <div className="w-full py-5 text-xs flex flex-col">
      <div className="flex justify-center items-center">
        <span>copyright (c) 2023</span>
        <Dot />
        <span>icedcoffeeee</span>
      </div>
      <div className="flex justify-center items-center">
        <ULButton nav="/privacy">privacy</ULButton>
        <Dot />
        <ULButton nav="/tos">terms of service</ULButton>
      </div>
    </div>
  );
}

function ULButton({ nav, children }: { nav: string } & PropsWithChildren) {
  return (
    <Link href={nav} className="hover:underline hover:cursor-pointer">
      {children}
    </Link>
  );
}

// src/components/Footer.svelte
<script lang="ts">
	export let additionalClass = '';
</script>

<footer
	class="px-4 w-full flex flex-col items-center lg:flex-row lg:justify-between gap-2 text-sm {additionalClass} "
>
	<div class="flex gap-6">
		<a href="/privacy">Privacy Policy</a>
		<a href="/terms">Terms of Service</a>
	</div>
	© LectCheck 2024
</footer>
